Unleash/unleash-android-sdk

unleashandroidsdk/src/main/java/io/getunleash/android/DefaultUnleash.kt
unleashandroidsdk/src/test/java/io/getunleash/android/DefaultUnleashTest.kt

Just checked that eventually the events might arrive out of order. Not sure if this would be a problem, I believe no as long as all events arrive. We have a buffer of 1000 events (maybe we should make it configurable, but I'd just wait until someone asks)

fix: we should emit events always if configured that way

---

unleashandroidsdk/build.gradle.kts

Try to fix
```
file '/home/runner/work/unleash-android/unleash-android/unleashandroidsdk/src/main/java/io/getunleash/android/events/HeartbeatEvent.kt' will be copied to 'main/io/getunleash/android/events/HeartbeatEvent.kt', overwriting file '/home/runner/work/unleash-android/unleash-android/unleashandroidsdk/src/main/java/io/getunleash/android/events/HeartbeatEvent.kt', which has already been copied there.
```

fix: sources already exist when packing

---

.github/workflows/build.yaml
.github/workflows/prs.yaml
unleashandroidsdk/build.gradle.kts

The [previous coverall report on main](https://coveralls.io/builds/68801615) was reporting a coverage of zero on DefaultUnleash despite having a lot of tests (and same with other classes and packages):
It looks like 
```
configure<JacocoTaskExtension> {
isIncludeNoLocationClasses = true
excludes = listOf("jdk.internal.*")
}
```
is required to get the reports properly. After this change this is my local report (note there are also some packages excluded which makes the coverage to raise):

fix: jacoco report proper coverage

---

unleashandroidsdk/src/test/java/io/getunleash/android/DefaultUnleashTest.kt

Not sure if this would fix it, but probably the first poll is kicking in and therefore messing up with the test.
This should make sure our test is not running the poll cycle but still keeping the polling enabled

chore: avoid flaky test

---

gradle/libs.versions.toml
unleashandroidsdk/build.gradle.kts
unleashandroidsdk/proguard-rules.pro
unleashandroidsdk/src/main/java/io/getunleash/android/DefaultUnleash.kt
unleashandroidsdk/src/main/java/io/getunleash/android/backup/LocalBackup.kt
unleashandroidsdk/src/main/java/io/getunleash/android/data/Parser.kt
unleashandroidsdk/src/main/java/io/getunleash/android/data/Variant.kt
unleashandroidsdk/src/main/java/io/getunleash/android/metrics/MetricsBucket.kt
unleashandroidsdk/src/main/java/io/getunleash/android/metrics/MetricsSender.kt
unleashandroidsdk/src/main/java/io/getunleash/android/polling/UnleashFetcher.kt
unleashandroidsdk/src/test/java/io/getunleash/android/BaseTest.kt
unleashandroidsdk/src/test/java/io/getunleash/android/data/PayloadTest.kt
unleashandroidsdk/src/test/java/io/getunleash/android/data/TestResponses.kt
unleashandroidsdk/src/test/java/io/getunleash/android/metrics/MetricsSenderTest.kt

Moshi is a much smaller library compared to jackson which allows us to reduce the overall bundle size

chore: migrate to moshi to reduce bundle size

---

README.md

According to our tests proguard rules are not needed for this library as they're part of the aar package

docs: remove proguard requirements

---

unleashandroidsdk/src/main/java/io/getunleash/android/UnleashConfig.kt
unleashandroidsdk/src/main/java/io/getunleash/android/data/DataStrategy.kt
unleashandroidsdk/src/main/java/io/getunleash/android/http/ClientBuilder.kt
unleashandroidsdk/src/test/java/io/getunleash/android/http/ClientBuilderTest.kt

Give users the ability of providing a custom okhttp client. Useful when you need to add custom SSL certificates.
We'll use the read, write and connection timeout from the configuration, so if any of those are added to the custom client we'll override those values (which are configurable).
Closes #84

feat: add ability to pass customer defined okhttp client

---

unleashandroidsdk/src/main/java/io/getunleash/android/data/Variant.kt

This complies with other SDKs. For reference we use NodeJS:
```typescript
const defaultVariant: IVariant = {
name: 'disabled',
enabled: false,
feature_enabled: false,
};
```

fix: variant enabled should be false by default

---

unleashandroidsdk/build.gradle.kts
unleashandroidsdk/src/main/java/io/getunleash/android/DefaultUnleash.kt
unleashandroidsdk/src/main/java/io/getunleash/android/polling/UnleashFetcher.kt
unleashandroidsdk/src/test/java/io/getunleash/android/DefaultUnleashTest.kt
unleashandroidsdk/src/test/java/io/getunleash/android/polling/UnleashFetcherTest.kt

Make sure we fetch when we setContextAsync, but also make sure we don't fetch twice when we setContext (sync method).
Fix #96

updated to use correct comparison for distinctUntilChanged

---

unleashandroidsdk/src/main/java/io/getunleash/android/polling/UnleashFetcher.kt

When skipping http calls due to throttling we should also count that we skipped that call so the throttler can recover. This is done in the metrics implementation: https://github.com/Unleash/unleash-android/blob/5c52d66e91e6ffa9c2d1ba5306a8d6663ae00c44/unleashandroidsdk/src/main/java/io/getunleash/android/metrics/MetricsSender.kt#L77-L79 but not in the feature toggle fetcher.
Closes #99
Maybe this can be refactored so the client of the throttler doesn't have to remember to call skipped. I have something like this in mind but it can be something good for a contribution, as I'm prioritizing fixing the bug.
```Kotlin
return throttler.execute {
Log.d(TAG, "Refreshing toggles")
val response = doFetchToggles(ctx)
fetcherHeartbeatFlow.emit(HeartbeatEvent(response.status, …
```

fix: when skipping a call due to throttle count one more skipped

---

.github/workflows/create-release.yml
.github/workflows/release.yml

When releasing from main the action does not execute in the tag ref, therefore it's being ignored: https://github.com/Unleash/unleash-android/actions/runs/12805063978
With this the workflow that creates the tag will be calling the workflow that publishes the SDK

chore: when releasing from main via GHA

---

unleashandroidsdk/build.gradle.kts
unleashandroidsdk/src/main/java/io/getunleash/android/UnleashConfig.kt

This PR adds standardised client identification headers to the feature and metrics calls that the client makes to Unleash. The headers are:
- `x-unleash-appname`: the name of the application that is using the client. 
- `x-unleash-connection-id`: a unique identifier for the current instance of the client generated by the built-in UUID lib
- `x-unleash-sdk`: sdk information in the format `unleash-client-android:<version>`
All the headers are intended for the Unleash team so clients should not be affected.
The main use cases we have are:
* capacity planning by knowing the number of unique connections made to the backend API
* debugging misconfigured SDKs sending more traffic than expected
* it seems that instanceId is not exposed to users in this SDK so I can re-use it for connection id
* …

feat: client identification headers

---

.github/workflows/release.yml
build.gradle.kts
unleashandroidsdk/build.gradle.kts

We got upgraded to the publishing portal this week (I upgraded us). This requires all our published project be published via the new portal. This PR configures https://github.com/yananhub/flying-gradle-plugin which should work (The needed api key has been added as a secret already)

chore: configure publish to maven portal

---

LICENSE
unleashandroidsdk/build.gradle.kts

Add MIT license, currently the repo doesn't have a license.
Closes #95

feat: add MIT license

---

.gitignore
app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
unleashandroidsdk/build.gradle.kts
unleashandroidsdk/src/main/java/io/getunleash/android/DefaultUnleash.kt

This PR makes the necessary changes to update the OkHttp dependency to 5.x.  OkHttp requires Kotlin 2.0 minimum, so I had to update the Kotlin version as well, and the compose-compiler plugin is due to a change required by Kotlin 2.x.  The compose compiler plugin is not applied in the SDK module.
The failure when updating OkHttp was happening due to the usage of an internal toImmutableList function in OkHttp.  Assuming you had a good reason to use an `ImmutableList` and not a standard readonly `List`, I added the kotlinx Immutable Collections dependency to replace the internal OkHttp usage.
Closes #98 
I did not include any versioning changes here because I am not sure how that process works for you guys internally.  Updating the kotlin version could be cause for a major version bump, but …

Update OkHttp to 5.1.0 and update Kotlin to 2.2.0

---

unleashandroidsdk/src/main/java/io/getunleash/android/http/NetworkStatusHelper.kt
unleashandroidsdk/src/test/java/io/getunleash/android/http/NetworkStatusHelperTest.kt

In the current version, the latest received event triggers the `onAvailable` and `onLost` methods, which start or stop jobs. The problem arises when many Android devices (for example, a Google Pixel running Android 15 - API 35) can handle multiple available networks simultaneously. In such cases, any single network loss will cause the jobs (polling and metrics) to stop, even though the device still has an active internet connection.
With this fix, `onLost` will only be called when all available networks are lost.
You should consider if you want to call `onAvailable` listener's code on each event received or only when is the first available network. I left this untouched mantaining the original behaviour but I think it should only be called the on the first one.

fix: network available listener

---

docs/MigrationGuide.md

Adds documentation about the environment property, used in the old SDK but removed from this one.
Closes #121

docs: add migation guide for environment property in old sdk

---

unleashandroidsdk/src/main/java/io/getunleash/android/metrics/MetricsBucket.kt
unleashandroidsdk/src/main/java/io/getunleash/android/metrics/MetricsReporter.kt
unleashandroidsdk/src/main/java/io/getunleash/android/metrics/MetricsSender.kt
unleashandroidsdk/src/main/java/io/getunleash/android/metrics/NoOpMetrics.kt
unleashandroidsdk/src/test/java/io/getunleash/android/DefaultUnleashTest.kt
unleashandroidsdk/src/test/java/io/getunleash/android/metrics/MetricsSenderTest.kt

This fixes a bug when submitting metrics; in the case of server failure, the SDK should hold on to the previous values to be able to send them later.
This currently doesn't keep the initial start time for the bucket, which leads to new buckets taking credit for metrics in the failed buckets

fix: metric submission failure should keep metrics for the next attempt

---

unleashandroidsdk/src/main/java/io/getunleash/android/util/UnleashLogger.kt

After internal conversations, we believe it's good enough to use log level configuration
With this PR we stop respecting Log.isLoggable and just rely on log level configuration
Closes #133

chore: refactor logging level check in UnleashLogger

---

unleashandroidsdk/src/main/java/io/getunleash/android/DefaultUnleash.kt
unleashandroidsdk/src/main/java/io/getunleash/android/Unleash.kt

As explained in issue #141, frontend SDKs should not provide a default value, as it may lead to incorrect behavior. 
The correct way of sending the expected initial state for features is through the bootstrap mechanism documented here: https://github.com/Unleash/unleash-android-sdk/?tab=readme-ov-file#step-4-option-2-provide-an-initial-state
A deprecation notice will instruct users to migrate to the method without a default value and link to the issue for more details.

fix: deprecate default parameters
